server:
  port: 9050
  # ONLY FOR TESTING
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

spring:
  application:
    name: rococo-auth
  mvc:
    log-request-details: true
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: postgres
    password: secret
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  kafka:
    bootstrap-servers: 'localhost:9092'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-auth'
  jpa:
    hibernate:
      ddl-auto: validate
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-auth:
  base-uri: 'http://127.0.0.1:9050'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  kafka:
    bootstrap-servers: 'kafka:9092'
  datasource:
    url: 'jdbc:postgresql://rococo-db:5432/rococo-auth'
  jpa:
    hibernate:
      ddl-auto: validate
rococo-front:
  base-uri: 'http://client.rococo.dc'
rococo-auth:
  base-uri: 'http://auth.rococo.dc:9050'
---